services:
  # Servicio de PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: db_webnotes
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_webnotes
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql

  # Servicio de la API
  api:
    build: .
    container_name: api_webnotes
    ports:
      - "3000:3000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=db_webnotes
      - PORT=3000
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres-data: